### ISSUE TITLE
set-up-project

### ISSUE THREAD

**Issue by IvonneBenitesRodriguez** [IvonneBenitesRodriguez/todo-list#1]
### Issue: set-up-project
- I will create the following files: index.html, style.css, and index.js 
- I will add a fontawesome icon.
- I will add a checkbox for the accomplished tasks
- I will add linters like Webhint, StyleLint, EsLint
- I will add a Form and create inside inputs so the user can add his/her tasks there

### Goal:
The goal of this project is to understand how to set up the webpack and its dependencies, 
also to understand and use ES6, construct an array of objects, loops, and the use of DOM.

**Comment by smas0900** [comment]
Your project is complete There is nothing else to say nice job
